### PR TITLE
update actions checkout@v3 setup-node@v3 with node16

### PR DESCRIPTION
**Pull request by heliomarpm**
# Update
- actions/checkout@v3
- actions/setup-node@v3 
   with: node-version: '>=16.8.0'

### CODE REVIEW

**Comment by gregorym** [comment]
bump

**Comment by marcofugaro** [comment]
@samuelmeuli could we merge this? otherwise this actions is dead

**Comment by teavver** [comment]
@samuelmeuli

**Comment by megahirt** [comment]
Looks like this action is dead.  We now need actions/checkout@v4 and actions/setup-node@v4 to get rid of node 16 warnings

**Comment by heliomarpm** [comment]
> Looks like this action is dead. We now need actions/checkout@v4 and actions/setup-node@v4 to get rid of node 16 warnings

I have made an updated version available
https://github.com/marketplace/actions/electron-builder-action-all-in-one

**Comment by megahirt** [comment]
> > Looks like this action is dead. We now need actions/checkout@v4 and actions/setup-node@v4 to get rid of node 16 warnings
> 
> I have made an updated version available https://github.com/marketplace/actions/electron-builder-action-all-in-one

@heliomarpm excellent!  Thank you for maintaining a fork and fixing this up!  I went to the fork but don't see an issue tracker (maybe that's intentional).

A request: could you name the tags with a 'v' e.g. 'v2.1'.  Currently you have just '2.1' which means that this fork isn't a drop in replacement for the samuelmeuli action - the version format also needs to be changed

**Comment by heliomarpm** [comment]
> > > Parece que essa ação está morta. Agora precisamos de ações/checkout@v4 e ações/setup-node@v4 para nos livrarmos dos avisos do nó 16
> > 
> > 
> > Disponibilizei uma versão atualizada https://github.com/marketplace/actions/electron-builder-action-all-in-one
> 
> Excelente! Obrigado por manter um garfo e consertar isso! Eu fui para o fork, mas não vejo um rastreador de problemas (talvez isso seja intencional).
> 
> Um pedido: você poderia nomear as tags com um 'v', por exemplo, 'v2.1'. Atualmente você tem apenas '2.1', o que significa que este fork não é uma gota em substituição para a ação samuelmeuli - o formato da versão também precisa ser alterado

Ok @megahirt , I'll do it.
tks

**Pull request closed without merging**
